[package]
name = "ambergracesoftware/dex-playersave"
version = "0.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
Dex = "ambergracesoftware/dex@0.1.7"
PlayerSave = "ambergracesoftware/playersave@0.0.2"